server:
  port: 18092


spring:
  application:
    name: seckill
  jackson:
    time-zone: GMT+8
    generator:
      write_numbers_as_strings: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.21.132:3306/changgou_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: 123456

  redis:
    host: 192.168.21.132
    port: 6379
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: 192.168.21.132
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
#开启Feign的熔断:默认是线程池隔离
feign:
  hystrix:
    enabled: true

#hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE